# Site
repository: enriqueRR/modern-resume-theme
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Enrique Reyes Reyes
title: SR Developer Ruby on Rails
email: ingenriquerreyes@gmail.com
phone: "7224174134"
website: https://ingenriqueresume.herokuapp.com/

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: 
github_username: enriqueRR
stackoverflow_username: "13868692"
linkedin_username: enrique-reyes-reyes-1b297819
facebook_username: 
instagram_username: 

# Additional icon links
additional_links:
- title: WebUniversity
  icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: https://webuniversity.herokuapp.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: https://avatars2.githubusercontent.com/u/100208?s=460&v=4
about_content: > # 
    I participated in business projects mainly related to the banking and insurance business,
    using different programming languages. I have 12 years of work experience in different types of roles and different information technologies.
    In this time I have contributed to the delivery of projects within the deadlines and quality standards established in the different companies. 
    I love Ruby on Rails for its simplicity and speed of development.
# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: > #
  I am interested in cryptocurrencies and the development of applications with Ruby for the transaction with cryptocurrencies. 
  The way I started to get interested. January 2017. A friend asked me if I had bought Bitcoin.
  I confess that I had no idea what he was talking about. Today I know I should have bought years ago. 
  Now a Bitcoin costs $ 17000 and it keeps going up.
  I have the ability to collaborate with work teams as a leader or project manager
  I consider that I have the ability to solve problems to deliver projects on time.
  Since 2005 I have been interested in ruby on rails, but because I couldn't find job offers.
  I was leaving it alone as a good example of a framework and I got into the world of Java.
  But today with all these changes, this year I have reconsidered going back to the good side of programming :-)

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

data_dir: _test/_data

include:
 - _test

exclude:
  - vendor

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
